### ISSUE TITLE
[BUG]: does this work when you have two on the same page?

### ISSUE THREAD

**Issue by williamsbdev** [nchristus/ember-cli-password-toggle#11]
We experienced an issue when we had two on the same page. I will check sometime this week to make sure that this still works.

**Comment by toranb** [comment]
I think we proved this does indeed support 2 components on a single page ... can we close this out?

**Comment by williamsbdev** [comment]
Yes. We have test cases. I think the situation I ran into had other issues. Thanks for reminder to close this out.
