### ISSUE TITLE
Placeholder text in password field

### ISSUE THREAD

**Issue by nicodv** [nchristus/ember-cli-password-toggle#18]
Is/would it be possible to add placeholder text in the password field, in the same way [ember's `{{input}}` helper offers a `placeholder` option](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_input)?

**Comment by toranb** [comment]
It should be possible - let me take a run at it this week and report back :)

**Comment by toranb** [comment]
This should now be available in v1.6.0 :)

**Comment by nicodv** [comment]
Awesome, thanks for quick turnaround!
