### ISSUE TITLE
Default the autocomplete attribute to off

### ISSUE THREAD

**Issue by benkiefer** [nchristus/ember-cli-password-toggle#23]
When a password is entered in the clear (show is toggled), the browser will store the input value and prompt future users of the form to use that password (in the clear later).

To get around this, you can set the autocomplete attribute to "off" manually on every password input, but it seems like the base version of this plugin could default that attribute to "off", at least when show is toggled.

There are other [values](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) that can be passed for this attribute, but in the testing I've done, when show is toggled on this input, the browser still gets overly excited and stores things it shouldn't.

Thoughts?

**Comment by nchristus** [comment]
https://github.com/nchristus/ember-cli-password-toggle/pull/24
