### ISSUE TITLE
Custom classes not being recomputed

### ISSUE THREAD

**Issue by denychen** [nchristus/ember-cli-password-toggle#26]
Is there a reason why the [custom classes](https://github.com/nchristus/ember-cli-password-toggle/blob/master/addon/components/password-toggle.js#L36-L44) aren't being recomputed when the dependent properties are changed?

I'm trying to apply a custom `inputClass` only if no password is supplied 
```javascript
inputClass=(if missingPassword 'u__error-borders')
```
but `inputClass` stays as the initial value of `undefined`.

**Comment by toranb** [comment]
@denychen is it possible to throw this together in a twiddle so we can see how it looks?

**Comment by denychen** [comment]
@toranb, something like [this](https://ember-twiddle.com/5a35473725635d041da4986fe813ef80).

**Comment by denychen** [comment]
@toranb, I've created a PR with the changes I have in mind. Please let me know what you think when you get a chance!

**Comment by toranb** [comment]
@denychen thanks again! This was published as v2.1.0 on npm
