### ISSUE TITLE
Publish version 3.1.0 to npm

### ISSUE THREAD

**Issue by arnagock** [nchristus/ember-cli-password-toggle#33]
Version 3.1.0 ember-cli-password-toggle contains a fix from @gion-andri 

It is referenced as the current version on github but was not published to npm. See:
https://www.npmjs.com/package/ember-cli-password-toggle

Could you please publish it? 

Thanks Adrian

**Comment by toranb** [comment]
@arnagock sorry for the delay - I've tagged the v3.1.0 release on github and published the package to npm

https://github.com/nchristus/ember-cli-password-toggle/releases
